### ISSUE TITLE
Speaker recognition tickbox option missing

### ISSUE THREAD

**Issue by menelic** [jojojaeger/asr#6]
model selection and transcription work, but regardless which model is chosen, the speaker recognition tick box is missing:

![image](https://github.com/jojojaeger/whisper-streamlit/assets/5934115/9a2bac2d-dfba-4e0e-ab51-99df1be28dad)

**Comment by jojojaeger** [comment]
i moved it out of the repo - you can access it now, i will push it! 
but you have to install https://pypi.org/project/pyannote.audio/ for that

**Comment by menelic** [comment]
thanks - can you add this as a dependency so its pulled while installing? In the install instructions of pyannote I saw conda is required, so I am wondering if pyanot can be added to a pre-existing install of whisper-streamlit. I will try later, if just installing it works, but there might be issues and I might not be the only one wondering about this..... ;-)

**Comment by menelic** [comment]
I can see that the new whisper-streamlit-speaker folder contains all the folders and files from the main app.  Do I just git pull whisper streamlit to install it or do I git pull just the whisper-streamlit-speaker folder?

in the whisper-streamlit readme you write:
still experimental, available in whisper-streamlit-speaker folder

the readme in that folder does not have that note, but also does nt specify which folder the generic install instruction listed there is referring to. 

Sorry for a n00b question, but please clarify in the readme so that less python savvy folk know how to install the version with diarisation.

**Comment by jojojaeger** [comment]
exactly you just need the whisper-streamlit-speaker folder

**Comment by menelic** [comment]
did that, and when I installed pyannote.audio it installed a lot of huge dependencies such as torch wheels etc. without any errors, except in the end: 

ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count


it also claims ModuleNotFoundError: No module named 'pyannote.audio'

despite it having been installed. This is part of the following app exception that occurs on start (streamlit loads but display only this error message)

2023-05-31 22:06:25.511 Uncaught app exception
Traceback (most recent call last):
  File "/home/.../.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 562, in _run_script
    exec(code, module.__dict__)
  File "/home/...//software/whisper-streamlit-speaker/Transcribe.py", line 2, in <module>
    from transcriber import Transcription
  File "/home/.../Documents/software/whisper-streamlit-speaker/transcriber.py", line 3, in <module>
    from pyannote.audio import Pipeline
ModuleNotFoundError: No module named 'pyannote.audio'
2023-05-31 22:07:19.667 Uncaught app exception
Traceback (most recent call last):
  File "/home/../.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 562, in _run_script
    exec(code, module.__dict__)
  File "/home/...//software/whisper-streamlit-speaker/Transcribe.py", line 2, in <module>
    from transcriber import Transcription
  File "/home/...//software/whisper-streamlit-speaker/transcriber.py", line 3, in <module>
    from pyannote.audio import Pipeline
ModuleNotFoundError: No module named 'pyannote.audio'

a second attempt results in the same error but confirms pyannote.audio is present:
  Using cached pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard>=2.2.0->pytorch-lightning<1.7,>=1.5.4->pyannote.audio) (3.2.0)
